version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection="Host=shuttle.proxy.rlwy.net;Port=35349;Database=railway;Username=postgres;Password=sDpaBIECVljVWiKRClohCGsuMfqwBGVp;SSL Mode=Require;Trust Server Certificate=true"
