version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    environment:
      SA_PASSWORD: "zaq1!xsw2@" 
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: unless-stopped
